ARDUINO_DIR  = /usr/share/arduino

BOARD_TAG    = atmega328
ARDUINO_PORT = /dev/serial/by-id/usb-FTDI_FT232R_USB_UART_A70078Q1-if00-port0

TARGET       = brmdoor

ARDUINO_LIBS = SoftwareSerial AdafruitPN532

include /usr/share/arduino/Arduino.mk
